module CanvasInlinePdf
  VERSION: String

  extend Preview
  extend Plugin

  module Plugin
    self.@cfg : Hash[Symbol, untyped]
    self.@name : Symbol

    def self.override_file_preview?: () -> bool
    def self.register: () -> void

    def register_plugin: () -> void
    def override_file_preview?: () -> bool

    module AttachmentExtension
      def inline_content?: () -> bool
    end

    class OverrideFilePreview
      include ::AbstractController::Callbacks::ClassMethods::_BeforeActionCallback

      # private methods.
      def allowed?: (ActionController::Base, untyped) -> bool

      def enabled?: () -> bool

      def mark_seen: (ActionController::Base, untyped) -> untyped
    end
  end

  module Preview
    interface _HasContent
      def content_type: () -> String
    end

    interface _HasUrl
      def public_url: (expires_in: Integer) -> String
    end

    def previewable?: (nil, _HasContent) -> bool
    def preview_url: (_HasUrl) -> String
  end
end
