name: Publish Gem

env:
  CI: true
  CI_TARGET: canvas_inline_pdf-${{ github.ref_name }}.gem
  REGISTRY: https://rubygems.pkg.github.com/${{ github.repository_owner }}

run-name: ${{ github.actor }} is publishing the gem

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1.6'

      - name: Run the unit tests.
        run: bundle exec rspec -f progress

      - name: Build The Gem.
        run: gem build canvas_inline_pdf.gemspec

      - name: Verify the gem matches the tag.
        id: verify_gem_version
        run: |
          if [[ -e "${CI_TARGET}" ]]; then
            echo "check_result=true" >> $GITHUB_OUTPUT
          else
            echo "The gem created does not match ${CI_TARGET}"
            exit 1
          fi

      - name: Publish the Gem.
        if: steps.verify_gem_version.outputs.check_result == 'true'
        run: gem push --key "${GITHUB_TOKEN}" --host "${REGISTRY}" ${CI_TARGET}
