name: Unit Tests
run-name: ${{ github.actor }} is running the unit tests.
on: [pull_request]
jobs:
  unit-tests:
    strategy:
      matrix:
        ruby:
          - '3.1.6'
          - '3.2.7'
          - '3.3.7'
          - '3.4.2'
        platform:
          - 'ubuntu-22.04'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run the unit tests.
        run: bundle exec rspec -f json -o tmp/rspec_results.json -f failures
      - name: Unit Test Report
        uses: SonicGarden/rspec-report-action@v6
        if: always()
        with:
          json-path: tmp/rspec_results.json
          title: '# :cold_sweat: Rspec (${{ matrix.ruby }}) failure.'
      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.4.0
        if: always()
        with:
          lcov-file: ./coverage/lcov/ruby-simplecov.lcov
          title: 'Coverage (${{ matrix.ruby }})'
